CREATE TABLE SALES_ORDER(
  ORD_NUM     INT,       
  ORD_DATE    DATETIME,  
  CUS_ID      INT,  
  EMP_NUM     INT,
  ORD_TC      CHAR(3),
  PRIMARY KEY(ORD_NUM)
); 

CREATE TABLE BILL_OF_LADING(
  LAD_NUM     INT,
  SHIP_ID     VARCHAR(10),
  ORD_NUM     INT,
  EMP_NUM     INT,
  LAD_DATE    DATETIME,
  PRIMARY KEY(LAD_NUM)
);

CREATE TABLE REMITTANCE_SINGLE(
  REM_NUM      INT,
  REM_DATE     DATETIME,
  REM_AMOUNT   NUMERIC(10,2),
  CUS_ID       VARCHAR(10),
  INV_NUM      INT,
  ACCT_NUM     INT,
  PRIMARY KEY(REM_NUM)
);

CREATE TABLE CUSTOMER(
  CUS_ID      VARCHAR(10),
  CUS_NAME    NVARCHAR(10),
  CUS_BA      NVARCHAR(50),
  CUS_SA      NVARCHAR(50),
  CUS_CR      VARCHAR(5),
  CUS_PHONE   VARCHAR(10),
  CUS_FAX     VARCHAR(15),
  CUS_MAIL    VARCHAR(30),
  CUS_IC      NVARCHAR(10),
  PRIMARY KEY(CUS_ID)
);

CREATE TABLE EMPLOYEE(
  EMP_NUM         INT,
  EMP_NAME        NVARCHAR(10),
  EMP_DEP_NUM     INT,
  EMP_HIRE_DATE   DATETIME,
  EMP_PHONE       VARCHAR(10),
  EMP_ID          VARCHAR(10),
  EMP_MAIL        VARCHAR(30),
  EMP_GENDER      NCHAR(1),
  EMP_BIRTHDAY    DATETIME,
  EMP_ADDRESS     NVARCHAR(50),
  PRIMARY KEY(EMP_NUM)
);


CREATE Table DEPARTMENT(
  DEPT_NUM    INT,
  DEPT_NAME   NVARCHAR(15),
  PRIMARY KEY(DEPT_NUM)
);
