CREATE TABLE INVENTORY(
  INVT_ID      VARCHAR(10),
  INVT_NAME    NVARCHAR(10),
  INVT_QOH     INT,
  INVT_RP      INT,
  INVT_SC      INT,
  INVT_RQ      INT,
  PRIMARY KEY(INVT_ID)
); 

/*  */

CREATE TABLE SALES_ORDER(
  ORD_NUM     INT,       
  ORD_DATE    DATETIME,  
  ORD_TC      CHAR(3),
  PRIMARY KEY(ORD_NUM)
); 

/*  */

CREATE TABLE SALES_ORDER_LINE(
  INVT_ID               VARCHAR(10),
  ORD_NUM               INT,
  ORD_LINE_QUANTITY	INT, 
  ORD_LINE_AMOUNT	INT, 
  PRIMARY KEY (INVT_ID, ORD_NUM)
);

/*  */

CREATE TABLE BILL_OF_LADING(
  LAD_NUM     INT,
  LAD_DATE    DATETIME,
  PRIMARY KEY(LAD_NUM)
);

/*  */

CREATE TABLE INVOICE(
  INV_NUM     INT,
  INV_DATE    DATETIME,
  INV_AMOUNT  INT,
  PRIMARY KEY(INV_NUM)
);

/*  */

CREATE TABLE REMITTANCE_SINGLE(
  REM_NUM      INT,
  REM_DATE     DATETIME,
  REM_AMOUNT   NUMERIC(10,2),
  PRIMARY KEY(REM_NUM)
);

/*  */

CREATE TABLE ACCOUNT(
  ACCT_NUM      INT,
  ACCT_BALANCE  INT,
  PRIMARY KEY(ACCT_NUM)
);

/*  */

CREATE TABLE CUSTOMER(
  CUS_ID      VARCHAR(10),
  CUS_NAME    NVARCHAR(10),
  CUS_BA      NVARCHAR(50),
  CUS_SA      NVARCHAR(50),
  CUS_CR      VARCHAR(5),
  CUS_PHONE   VARCHAR(10),
  CUS_FAX     VARCHAR(15),
  CUS_MAIL    VARCHAR(30),
  CUS_IC      NVARCHAR(10),
  PRIMARY KEY(CUS_ID)
);

/*  */

CREATE TABLE SHIPPING_COMPANY(
  SHIP_ID       VARCHAR(10),
  SHIP_NAME     NVARCHAR(10),   
  SHIP_ADDRESS  NVARCHAR(50),  
  SHIP_PHONE    VARCHAR(10),    
  SHIP_FAX      VARCHAR(20),                   
  SHIP_MAIL     NVARCHAR(50),    
  SHIP_RP  　   NVARCHAR(10),
  PRIMARY KEY(SHIP_ID)
);

/*  */

CREATE TABLE EMPLOYEE(
  EMP_NUM         INT,
  EMP_NAME        NVARCHAR(10),
  EMP_HIRE_DATE   DATETIME,
  EMP_PHONE       VARCHAR(10),
  EMP_ID          VARCHAR(10),
  EMP_MAIL        VARCHAR(30),
  EMP_GENDER      NCHAR(1),
  EMP_BIRTHDAY    DATETIME,
  EMP_ADDRESS     NVARCHAR(50),
  PRIMARY KEY(EMP_NUM)
);

/*  */

CREATE Table DEPARTMENT(
  DEPT_NUM    VARCHAR(5),
  DEPT_NAME   NVARCHAR(15),
  PRIMARY KEY(DEPT_NUM)
);

/*  */

CREATE TABLE 　BANK(
  BANK_CODE     VARCHAR(10),
  BANK_NAME     NVARCHAR(10),
  BANK_PHONE    VARCHAR(10),
  BANK_ADDRESS  NVARCHAR(50),
  PRIMARY KEY(BANK_CODE)
);

/*  */

CREATE TABLE　VENDOR(
  VEN_ID      VARCHAR(10),
  VEN_NAME    NVARCHAR(10),
  VEN_PHONE   VARCHAR(10),
  VEN_FAX     VARCHAR(15),
  VEN_MAIL    VARCHAR(30),
  VEN_IC      NVARCHAR(10),
  PRIMARY KEY(VEN_ID)
);

/*  */

CREATE TABLE　WAREHOUSE(
  WHSE_NUM      INT,
  WHSE_ADDRESS  NVARCHAR(50),        
  WHSE_PHONE    VARCHAR(10),  
  PRIMARY KEY(WHSE_NUM)
);


/* ADD INVENTORY FOREIGN KEY*/
ALTER TABLE INVENTORY ADD VEN_ID　VARCHAR(10);
ALTER TABLE INVENTORY ADD WHSE_ID INT;
ALTER TABLE INVENTORY ADD FOREIGN KEY(VEN_ID) REFERENCES VENDOR ON UPDATE CASCADE;
ALTER TABLE INVENTORY ADD FOREIGN KEY(WHSE_ID) REFERENCES WAREHOUSE ON UPDATE CASCADE;

/* ADD SALES_ORDER FOREIGN KEY*/
ALTER TABLE SALES_ORDER ADD CUS_ID VARCHAR(10);
ALTER TABLE SALES_ORDER ADD EMP_NUM INT;
ALTER TABLE SALES_ORDER ADD FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER ON UPDATE CASCADE;
ALTER TABLE SALES_ORDER ADD FOREIGN KEY(EMP_NUM) REFERENCES EMPLOYEE ON UPDATE CASCADE;

/* ADD SALES_ORDER_LINE FOREIGN KEY*/
ALTER TABLE SALES_ORDER_LINE ADD FOREIGN KEY(ORD_NUM) REFERENCES SALES_ORDER ON UPDATE CASCADE;
ALTER TABLE SALES_ORDER_LINE ADD FOREIGN KEY(INVT_ID) REFERENCES INVENTORY ON UPDATE CASCADE;

/* ADD BILL_OF_LADING FOREIGN KEY*/
ALTER TABLE BILL_OF_LADING ADD SHIP_ID VARCHAR(10);  
ALTER TABLE BILL_OF_LADING ADD ORD_NUM INT;
ALTER TABLE BILL_OF_LADING ADD EMP_NUM INT;
ALTER TABLE BILL_OF_LADING ADD FOREIGN KEY(SHIP_ID) REFERENCES SHIPPING_COMPANY ON UPDATE CASCADE; 
ALTER TABLE BILL_OF_LADING ADD FOREIGN KEY(ORD_NUM) REFERENCES SALES_ORDER ON UPDATE CASCADE;
ALTER TABLE BILL_OF_LADING ADD FOREIGN KEY(EMP_NUM) REFERENCES EMPLOYEE ON DELETE CASCADE;

/* ADD INVOICE FOREIGN KEY*/
ALTER TABLE INVOICE ADD CUS_ID VARCHAR(10);
ALTER TABLE INVOICE ADD LAD_NUM　INT;
ALTER TABLE INVOICE ADD FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER ON UPDATE CASCADE;
ALTER TABLE INVOICE ADD FOREIGN KEY(LAD_NUM) REFERENCES BILL_OF_LADING ON DELETE CASCADE;

/* ADD REMITTANCE_SINGLE FOREIGN KEY*/
ALTER TABLE REMITTANCE_SINGLE ADD CUS_ID VARCHAR(10);
ALTER TABLE REMITTANCE_SINGLE ADD INV_NUM INT;  
ALTER TABLE REMITTANCE_SINGLE ADD ACCT_NUM INT;  
ALTER TABLE REMITTANCE_SINGLE ADD FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER ON UPDATE CASCADE;
ALTER TABLE REMITTANCE_SINGLE ADD FOREIGN KEY(INV_NUM) REFERENCES INVOICE ON DELETE CASCADE; 
ALTER TABLE REMITTANCE_SINGLE ADD FOREIGN KEY(ACCT_NUM) REFERENCES ACCOUNT ON UPDATE CASCADE; 

/* ADD ACCOUNT FOREIGN KEY*/
ALTER TABLE ACCOUNT ADD BANK_CODE VARCHAR(10);
ALTER TABLE ACCOUNT ADD FOREIGN KEY(BANK_CODE) REFERENCES BANK ON UPDATE CASCADE;

/* ADD EMPLOYEE FOREIGN KEY*/
ALTER TABLE EMPLOYEE ADD DEPT_NUM VARCHAR(5)
ALTER TABLE EMPLOYEE ADD FOREIGN KEY(DEPT_NUM) REFERENCES DEPARTMENT ON UPDATE CASCADE;

/* ADD WAREHOUSE FOREIGN KEY*/
ALTER TABLE WAREHOUSE ADD EMP_NUM INT;
ALTER TABLE WAREHOUSE ADD FOREIGN KEY(EMP_NUM) REFERENCES EMPLOYEE ON DELETE CASCADE;

